[build]
  publish = "."
  command = "echo 'No build command needed for static files'"

[[redirects]]
  from = "/api/*"
  to = "https://cosmic-monads-api.herokuapp.com/api/:splat"
  status = 200
  force = true

[functions]
  directory = "netlify/functions" 